### ISSUE TITLE
96 Megabytes....

### ISSUE THREAD

**Issue by rasmusbergpalm** [walletgeneratornet/WalletGenerator.net#108]
It's UUUUYE!

What's up with that? It's supposed to be a few thousand lines of JS?
This is supposed to be the light, fast, grunpy backender, green terminal crypto geek, version of a wallet. 
Do we really need 150+ logos and a separate paper wallet for each?
Can't we just have a name on the wallet, e.g. dogecoin, bitcoin, etc.?

Seriously though. Thanks. Awesome software. Consider the size.

**Comment by MichaelMure** [comment]
Well, any project is made of compromise. This project produce nice and fancy paper wallet, so it needs nice and fancy background and logo.

The size start to be a problem though with the addition of so much currencies. It could be more efficient but this way to do things helps people to contribute so it will stay that way until it become really a problem or if someone take care of that.
