### ISSUE TITLE
sha256sum changing values

### ISSUE THREAD

**Issue by Khaezzar** [walletgeneratornet/WalletGenerator.net#112]
I have done sha256sum on multi-downloaded files but can t get the same signature :
do I make a mistake ?

on my computer yesterday : 
9e518487d05116f96a78a8719c229142a9c7e6b08225df7d78ea0d534d7f2419  WalletGenerator.net-master.zip

on another computer today :
71fd8382aced9186ff262d390d11a0ec18021bae363bb29015ec3d203eb85e73  Downloads/WalletGenerator.net-2017.10.25(2).tar.gz
2f2cad603aa22af51ea18ec543a25e6afdf46ada12e792e5a3ba3701bf1f0578  Downloads/WalletGenerator.net-2017.10.25.zip
e3ba7f20bea92c399dfa49725c341d57e1617c47a038a94748dc898e7e7e1f39  Downloads/WalletGenerator.net-master.zip

the two master are different.
is the master and the last release zip different ?

**Comment by MichaelMure** [comment]
I merged some pull-request yesterday (https://github.com/MichaelMure/WalletGenerator.net/commits/master) so you have two different versions. That's perfectly normal.

If you want to do proper comparaison, you should use the released version (https://github.com/MichaelMure/WalletGenerator.net/releases)
