### ISSUE TITLE
не могу снять монеты с walletgenerator

### ISSUE THREAD

**Issue by vitali333** [walletgeneratornet/WalletGenerator.net#131]
здравствуйте
зашёл в свой кошелёк на walletgenerator - как посмотреть баланс и перевести монеты ???
на другом кошельке просит  ---Введите кодовую фразу BIP38---- можно ли зайти без неё ??
спасибо

**Comment by pantuchy** [comment]
Если Вы создавали кошелек и секретный ключ с кодовой фразой, то без нее вы кошелек не откроете. Вспоминайте кодовую фразу. Надо будет сначала открыть с этой фразой кошелек, затем импортировать секретный ключ, тогда сможете управлять средствами. А баланс можно посмотреть на блокчейне вашей монеты или тут: https://chainz.cryptoid.info/ или https://bchain.info/MOON/ или на подобных сервисах. Там достаточно указать кошелек, и увидите баланс. Секретный ключ там не нужен.

**Comment by vitali333** [comment]
Здравствуйте. У меня есть и номер кошелька и кодовая фраза. Я их ввожу и просто вижу свой номер кошелька и фразу + штрих коды. Я не нашёл кнопки перевести или снять. Перерыл весь интернет - не получается. У меня монеты - електра и мун. Заходил к ним на сайт и скачал прогу. Но снять так и не получилось.Спасибо4 янв. 2018 г. 3:14 пользователь Maksim Pol <notifications@github.com> написал:Если Вы создавали кошелек и секретный ключ с кодовой фразой, то без нее вы кошелек не откроете. Вспоминайте кодовую фразу. Надо будет сначала открыть с этой фразой кошелек, затем импортировать секретный ключ, тогда сможете управлять средствами. А баланс можно посмотреть на блокчейне вашей монеты или тут: https://chainz.cryptoid.info/ или https://bchain.info/MOON/ или на подобных сервисах. Там достаточно указать кошелек, и увидите баланс. Секретный ключ там не нужен.
