### ISSUE TITLE
How To Use

### ISSUE THREAD

**Issue by mfread** [walletgeneratornet/WalletGenerator.net#136]
Hi Micahel/all. 

Sorry but I didn't know where else to ask this question. The README file doesn't tell me how to use this app/script, and the index.html is confusing (multiple tabs). For example, the addresses on the 'Single Wallet' tab do not correspond to the ones on the 'Paper Wallet' tab, yet the instructions given on the SW tab reference the PW tab.

So I'm guessing the SW tab is just that - you choose your currency (presumably this is important?), click on the 'Generate New Address' button, and write down the public and private keys into say a text file on my computer. The text file can be encrypted on my computer, but if I print out the text file the private key will be 'in-the-clear'. I'm also guessing I could copy and paste the entire block (keys and QR codes) and paste into say a Microsoft Word document on my PC (again, printing this document would reveal the private key in-the-clear).

Same goes for the 'Bulk Wallet' I'm guessing too (generate say 5 public & private key pairs). Do I need to specify a currency? Does each currency change the way the keys are generated?

Perhaps the reason for the private keys (for SW and BW) are in-the-clear because that's the only way you can import them into other tools and apps like an exchange?

Now the PW tab has me intrigued. Seems that in order to generate new keys I press the 'Randomly Generate' button (as I see the keys change when I do so). Ok, so-far-so-good. Pressing the BIP38 button changes the QR codes but not the keys themselves - interesting - so what's going on? When should I use BIP38? When do I use the Passphrase?

When do I use the "Enter your own WIF private key" textbox? Presumably if I want to use one of the private keys on the SW or BW tabs?

As you can see, a document describing each tab and the order in which one is to enter data on the Paper Wallet tab would be very useful.

Many thanks,
Mark

**Comment by MichaelMure** [comment]
> For example, the addresses on the 'Single Wallet' tab do not correspond to the ones on the 'Paper Wallet' tab

These tabs are independent.

> you choose your currency (presumably this is important?),

Yes. Please take the time to understand what you are doing.

> Does each currency change the way the keys are generated?

Yes

> When should I use BIP38

Bip38 allow you to encrypt your paper wallet so that someone finding it still need a passphrase to use the funds.

> When do I use the "Enter your own WIF private key" textbox? Presumably if I want to use one of the private keys on the SW or BW tabs?

Its if you want to print a wallet with a key from somewhere else.
