### ISSUE TITLE
Maza Wallet private key broken

### ISSUE THREAD

**Issue by LutzLange** [walletgeneratornet/WalletGenerator.net#143]
I did use this, probably online back in March or April 2014 to generate a paper wallet for Maza Coin. My private key starts with 6y... 

This key does not work and I don't have access to my funds on this address. It looks like this has been encoded the wrong way. I need help to find out how to convert the key I have into a working WIF format. 

I tried the old releases of the Wallet Generator but have not found a version yet that produces priv keys for Maza that start with 6... they all start with 8 now.

**Comment by LutzLange** [comment]
It looks like I generated "MegaCoin" paper wallets and this is why I can't access my funds. Is there any way  get this right? Can I somehow extract my private key and get access to the address that now has my funds?

**Comment by LutzLange** [comment]
What is odd is that the address did work to deposit funds. It looks like I have the same problem with the Qubit Coin. This can't be a coincidence. I'm hoping for a chance that just the private key format was off for me. I know that you can get at the private keys and can build correct WIF private keys form import into the wallets. How would I do that?

**Comment by MichaelMure** [comment]
Mazacoin and Megacoin have the same public address format, so your funds should be fine. What you have to do is to fix the private key to be imported properly:
- open walletgenerator to the 'wallet detail' tab, select the 'megacoin' currency and enter your private key to be decoded
- copy the `Private Key Hexadecimal Format` value. This is your raw private key
- switch to the mazacoin currency and enter your raw private key to have the detail
- you should get a private key properly encoded now

**Comment by MichaelMure** [comment]
Please report here if it worked for you.

**Comment by LutzLange** [comment]
Thought I had this updated. 

Your procedure worked fine for me. Thank you so much!!
