### ISSUE TITLE
Trezarcoin Private Key not working.

### ISSUE THREAD

**Issue by tbrumer** [walletgeneratornet/WalletGenerator.net#146]
I have created a Trezarcoin wallet and transferred some funds to it, but when I tried to access it using the private key I received the message "The text you entered is not a valid Private Key! Would you like to use the entered text as passphrase..."
I already tried to create another wallets after that and got the same message every time.

Thank you for your attention.

**Comment by tbrumer** [comment]
I tried to create a new wallet using the "Would you like to use the entered passphrase text and create a Private Key using the SHA256 hash of the passphrase?" and then I tested the Private Keys. The Private Key WIF 51 characters Base58 doesn't seem to work, the others work just fine. Is there any way for me to withdraw the funds from my wallet that I mentioned above?

**Comment by MichaelMure** [comment]
Where are you trying to import your key ?

**Comment by tbrumer** [comment]
https://walletgenerator.net/?currency=TrezarCoin

At Wallet Details tab.

**Comment by MichaelMure** [comment]
Ha, I see indeed. There is a small mistake that make the private key not recognized properly.

I will fix that.

In the mean time, you can decode your TrezarCoin private key as if it was a TopCoin one (https://walletgenerator.net/?currency=Topcoin). The configuration is exactly how it should be for TrezarCoin.

**Comment by MichaelMure** [comment]
Fixed with 699dc534550f2baf3f6648736c22a4efcc188218
