### ISSUE TITLE
Wallet Generator doesn't work from inside the zip archive (windows)

### ISSUE THREAD

**Issue by tParkhilleaton** [walletgeneratornet/WalletGenerator.net#147]
I am not able to make the generator work.  The instructions on the Walletgenerator.net site are clear. After downloading the zip file, and open the index.html file, no choices are available. An overlay covers the working area and none of the buttons work. You cannot choose which coin you require, you cannot choose Single wallet or Paper wallet. You cannot choose Generate new wallet. The generator meanwhile is generating a wallet, but it has the overlay over the top and you cannot print. The generator is not working.

**Comment by MichaelMure** [comment]
It's working properly for me.

What browser do you use ? Can you show a screenshot of what you get ? Do you have the same problem with the online generator ?

**Comment by tParkhilleaton** [comment]
I am using Google Chrome. I have the same problem on line and off line. 
Screenshot (59) is the zip file downloaded from Github.
![screenshot 59](https://user-images.githubusercontent.com/35519994/35045705-66266874-fb9d-11e7-8778-fed904b9a9a0.png)
Screenshot (57) is the result of opening the index.html file which the generates the wallet. Notice the overlay. There is no place to select what coin I require or a button to select Generate new wallet.
![screenshot 57](https://user-images.githubusercontent.com/35519994/35045929-1d1a3fb0-fb9e-11e7-8670-aeae910e2235.png)
Screenshot (58) is the screen after the counter goes to "0". Notice the new overlay, the button to choose the coin now appears and does respond to allow selection. The button to generate a new wallet is under the over lay and the print button is visable but has no response.
![screenshot 58](https://user-images.githubusercontent.com/35519994/35046103-b9fab49a-fb9e-11e7-8031-bdc3db831a8d.png)
Please advise where I am making the mistake. Thanking you Michael

**Comment by MichaelMure** [comment]
Images are not loading and are replaced by oversized alt text.

Do you have a plugin in chrome that block images ?

**Comment by MichaelMure** [comment]
Also, you probably need to actually extract the zip archive.

**Comment by tParkhilleaton** [comment]
I will try to extract the zip archive. I am using Windows 10 and that unzipped the files.

**Comment by tParkhilleaton** [comment]
Thank you Michael, that worked. I used 7zip to unzip the file and then opened index.html and it works fine.
Sorry for the inconvenience and thanks again.

**Comment by MichaelMure** [comment]
No problem
