### ISSUE TITLE
Invalid wallet format for LiteCoin Private Key

### ISSUE THREAD

**Issue by admoseley** [walletgeneratornet/WalletGenerator.net#148]
I'm trying to import my paper wallet back to ANY litecoin wallet and i'm getting various errors.
I tried on litevault.net and Get "Error importing WIF. Please verify that the format is correct"
Also Exodus, Jaxx, litecoin core and loafwallet. I did use the encryption phrase to secure the crypto, but im lost on how to retrieve my litecoin.
I can go out to the block chain and verify that the funds are still there.

**Comment by MichaelMure** [comment]
If you used Bip38 encryption, you have to go to the "wallet detail" tab of walletgenerator to decrypt your private key before importing it in a software wallet.

**Comment by MichaelMure** [comment]
Closing, feel free to reopen if needed.

**Comment by admoseley** [comment]
I'd all but given up hope and didnt realize you responded to this post.
I was able to restore 5 litecoins. Thank you!
