### ISSUE TITLE
Can't import Fujicoin privkey

### ISSUE THREAD

**Issue by fujicoin** [walletgeneratornet/WalletGenerator.net#18]
Hi WalletGenerator.net,

Thank you for listing Fujicoin.

I tested private key generated by your WalletGenerator. 
In the wallet console, I put command:
  importprivkey 5J9Q31kRr5FUEfdz6z6oqByJtdALtvQpykVCqfpQGxKNcmBMF7w
console returned:
  Invalid private key (code -5)

There is something wrong. What is it?

Thanks.
motty

**Comment by fujicoin** [comment]
Hi WalletGenerator.net,

Please correct the bug.
janin.currency.createCurrency ("Fujicoin",   0x24, 0x80, "5",    "[KL]" ,

to
janin.currency.createCurrency ("Fujicoin",   0x24, 0xa4, "6",    "R"    ,

Thanks.
motty

**Comment by MichaelMure** [comment]
It's fixed now, thanks.
