### ISSUE TITLE
List of wrong coin

### ISSUE THREAD

**Issue by fujicoin** [walletgeneratornet/WalletGenerator.net#19]
**List of wrong coin:**

Coin        bHEX    cHEX    d   e   bDEC    cDEC    c-b
Acoin       17  E6  "8" "b" 23  230 207
Fuelcoin    24  80  "5" "[KL]"  36  128 92
Fujicoin    24  80  "5" "[KL]"  36  128 92
iXcoin      8A  80  "5" "[LK]"  138 128 -10
Latium      17  80  "5" "[LK]"  23  128 105
LiteDoge    5A  AB  "6" "S" 90  171 81
Mazacoin    32  E0  "8" "a" 50  224 174
NameCoin    34  80  "5" "[LK]"  52  128 76
Nubits      19  BF  "7" "V" 25  191 166
Riecoin     3C  80  "5" "[LK]"  60  128 68
Unobtanium  82  E0  "8" "a" 130 224 94
VikingCoin  46  56  "3" "D" 70  86  16
WeAreSatoshi    87  97  6   P   135 151 16
Zetacoin    50  E0  "8" "a" 80  224 144

**Do not use this!**

**Comment by MichaelMure** [comment]
What's "wrong" with them ?

**Comment by fujicoin** [comment]
r u amateur? lol

**Comment by MichaelMure** [comment]
Ok, if you have actual technical information, feel free to reopen this bug and enlighten me.
