### ISSUE TITLE
Forgot private key

### ISSUE THREAD

**Issue by jasha1974** [walletgeneratornet/WalletGenerator.net#197]
Hello, it's possible get private key, which i generated on page? if i know public key and datetime a generated? from same server cache or something ? Thanx

**Comment by Randomblock1** [comment]
Nope. All addresses are generated entirely on your computer, the server just serves up the webpage, and it can't save any addresses. Hopefully you didn't send any coins over, because you can't ever find that address again. Doing that is next to impossible.

**Comment by jasha1974** [comment]
Yes,, i’ve sended :( its any possible find on my computer ? cache or samewhere ?

 

Thanx Slavik j.

**Comment by Randomblock1** [comment]
It's not stored anywhere, in case hackers break into your computer, so that your funds are safe. If you printed a paperwallet or saved a PDF with the address, you should be able to access it.
If not, your funds are gone forever. Nobody can do anything to get it back.

**Comment by walletgeneratornet** [comment]
Hi jasha1974,

I am terribly sorry but if you lost your private key or forgot to write it down there is nothing that can be done. No data is saved on the server, it is on your computer and when you close the browser it's gone.
