### ISSUE TITLE
Mooncoin

### ISSUE THREAD

**Issue by coinflow** [walletgeneratornet/WalletGenerator.net#2]
Hi Michael,

would you mind adding Mooncoin to the paper-wallet generator?

The source is here: https://github.com/realmooncoin/mooncoin (original project-pages) or here: https://github.com/mooncoin-project (new project-pages).
You can download a logo from here: http://mooncoin.rocks or from the new GitHub project-page above.

I'd gladly send you some Mooncoin to a Mooncoin-address of yours to test and for the work, as soon as you post your Mooncoin-address.

Here is a valid Mooncoin-address to check the format: 2aUbyWinjiSbBvhhkh7tKcP9hEZdEogZy9

The official wallet as a binary can be downloaded here: http://mooncoin.rocks/wallet-download

Thank you very much and best regards
coinflow

**Comment by MichaelMure** [comment]
Hi,

We will add it in our next update.

**Comment by coinflow** [comment]
Great. Thank you very much.
If you post your Mooncoin-address here, I'll send you some coins. I'll also post a link to this page in the thread on bitcointalk, so others can donate for your work, if they like.

Edit: Feel free to post your Mooncoin-address there, too. I'm sure you'll get some coins from the community. --> https://bitcointalk.org/index.php?topic=389403.msg9402885#msg9402885

**Comment by MichaelMure** [comment]
It's now online :-)

https://walletgenerator.net/?currency=MoonCoin

As you asked, here is our MoonCoin address: 2P2V9npcK7apbUFsWN3zL7R6ARBMwTJ4hA

**Comment by coinflow** [comment]
Thank you very much. I have just sent you some Mooncoin and will link this page to the Mooncoin-thread on bitcointalk, so others can send you some MOON for your awesome work, too.

Thanks again.

Edit: https://bitcointalk.org/index.php?topic=389403.msg9581920#msg9581920
