### ISSUE TITLE
Paper Wallet doesn't match Single Wallet

### ISSUE THREAD

**Issue by AbePralle** [walletgeneratornet/WalletGenerator.net#204]
When I Generate New Address on the default Single Wallet tab and switch to the Paper Wallet tab, the keys don't match.

They matched 10 days ago when I first used WalletGenerator.net.

I'm on macOS and have tried Vivaldi, Firefox, Chome, and Safari. I tried the web version as well as a local copy from GitHub.

I see there haven't been any GitHub updates in that time frame so I'm a little perplexed on how that could even happen.

**Comment by BCeder** [comment]
Is someone going to answer this question?  I found the same thing and was very upset to realize I almost used public address to another wallet.  Fortunately I always check them.... but now I am concerned if this glitch means my addresses are not correct.  Thank you.

**Comment by walletgeneratornet** [comment]
Hi AbePralle and BCeder,

It has always been this way, the Single Wallet and Paper Wallet pages have different keys on them.

**Comment by AbePralle** [comment]
1. In that case the instructions are wrong because they say to "1) Click Generate New Address and then 2) click Paper Wallet tab and print". Seems like switching to the Paper Wallet tab should be Step 1.

2. I could swear that it used to work differently because the first time I used this generator I copied & pasted the public key to email out and I also took a photo of the printed public key as a confirmation. You can't easily copy & paste the public key from the Paper Wallet tab (because it's a vertical selection that tends to grab public & private at the same time) and I don't remember doing that.

**Comment by BCeder** [comment]
Yes, I recall it that way too.  However, thanks for the answers.

**Comment by crines** [comment]
What you do is just as it states and if you do NOT click to another tab you have:
(1) the single wallet appearing on the screen. 

(2) If then, you click on the paper wallet tab the keys ARE different than those of the single wallet (which is used to quickly obtain an address to start a new wallet. On the Paper Wallet tab, once the image is displayed, and before you click to print it, you can select the characters of any key as normal (without them being hashed into the form in the .pdf file where it is impossible to just copy and paste the keys.

(3) Now that you have the key codes copied and saved, click to print the paper wallet with images which is appears on screen in the .pdf file format.

This worked for me ;)
Good luck, try it once more.

**Comment by crines** [comment]
What you do is just as it states and if you do NOT click to another tab you have:
(1) the single wallet appearing on the screen. 

(2) If then, you click on the paper wallet tab the keys ARE different than those of the single wallet (which is used to quickly obtain an address to start a new wallet. On the Paper Wallet tab, once the image is displayed, and before you click to print it, you can select the characters of any key as normal (before the key hashes are software encrypted, into the .pdf file, and it is impossible to just copy and paste the keys.

(3) Now that you have the key codes copied and saved, click to print the paper wallet with images which is appears on screen in the .pdf file format.

This worked for me ;)
Good luck, try it once more.

**Comment by crines** [comment]
What you do is just as it states and if you do NOT click to another tab you have:
(1) the single wallet appearing on the screen. 

(2) If then, you click on the paper wallet tab the keys ARE different than those of the single wallet (which is used to quickly obtain an address to start a new wallet). On the Paper Wallet tab, once the image is displayed, and before you click to print it, you can select the characters of any key as normal (before the key hashes are software embedded, into the .pdf file, and it is impossible to just copy and paste the keys.

(3) Now that you have the key codes copied and saved, click to print the paper wallet with images which appears on screen in the .pdf file format.

This worked for me ;)
Good luck, try it once more.
