### ISSUE TITLE
gridcoin only shows error message

### ISSUE THREAD

**Issue by treaki** [walletgeneratornet/WalletGenerator.net#29]
hi,

i tried to generate a gridcoin vallet using

https://walletgenerator.net/?currency=Gridcoin

but whatever i do i get only a javascript alert window that the given currency couldnt be found. Looks like a bug... please check that and keep me informed

thanks

![160105_gridcoin_walletgenerator net_error_](https://cloud.githubusercontent.com/assets/1477872/12111748/04df697a-b398-11e5-936f-cc6a85208dbf.png)

**Comment by MichaelMure** [comment]
Hi,

Gridcoin has been rebranded as GridcoinResearch (see https://github.com/MichaelMure/WalletGenerator.net/pull/22).

The correct url is thus https://walletgenerator.net/?currency=GridcoinResearch
