### ISSUE TITLE
Guldencoin

### ISSUE THREAD

**Issue by larsje099** [walletgeneratornet/WalletGenerator.net#32]
the name of the coin is changed from Guldencoin to Gulden

now we cant use the qr code to import private keys can you fix this?

Thanks,

Lars

**Comment by mjmacleod** [comment]
https://github.com/MichaelMure/WalletGenerator.net/pull/33

**Comment by MichaelMure** [comment]
Could you describe what exactly is broken because of the bad name ? IIRC, the name of the currency is not embedded in the qr code.

**Comment by larsje099** [comment]
When I'm importing the private key it's saying cannot classify input.

**Comment by larsje099** [comment]
On an android phone that is

**Comment by MichaelMure** [comment]
So you are using the camera Qr code scanner on android ? I didn't even thought it was possible.

On my android phone, the browser just refuse to access the camera.

**Comment by MichaelMure** [comment]
What browser on android do you use ?

**Comment by larsje099** [comment]
I have created an wallet on my pc and want to get my private on the phone so the qr from the website off my pc with my camera from my phone but then I'm getting that error

**Comment by MichaelMure** [comment]
The pull-request got merged, closing this.
