### ISSUE TITLE
Best address to support walletgenerator.net

### ISSUE THREAD

**Issue by ghost** [walletgeneratornet/WalletGenerator.net#34]
I understand that when the support for a currency has been added by an external contributor, they receive the donation directly. 

Is there a way to donate directly to the walletgenerator.net project? I assume using the BTC donation address but wanted to ask.

**Comment by Stoner19** [comment]
[https://github.com/MichaelMure/WalletGenerator.net/wiki/How-to-add-a-new-currency#step-seven-the-donation-address](url)

Leave the donation section blank and they'll add one themselves. I imagine it'll be currency specific for the sake of maintaining consistency with the code.

**Comment by ghost** [comment]
Thanks. Well, I don't know which ones they added themselves. I was interested finding out the best address to donate directly to walletgenerator itself, rather than an external contributor.

**Comment by MichaelMure** [comment]
Hi,

You can find who added each currency using the blame function, directly on github:
https://github.com/MichaelMure/WalletGenerator.net/blame/master/src/janin.currency.js#L79

BTC is fine.

**Comment by MichaelMure** [comment]
You can also look at the end of the donation page, the release notes list each external contributor.

**Comment by ghost** [comment]
Great advice, thank you!

**Comment by MichaelMure** [comment]
I guess that was you. It should cover the hosting fees for some times, thanks !
