### ISSUE TITLE
how to change default currency

### ISSUE THREAD

**Issue by cyberpay** [walletgeneratornet/WalletGenerator.net#44]
wondering how to change default currency from BTC to any other alt. when alt is defined among all it worked however i doesnt want user to choose currency from drop down or LHS selection area

**Comment by MichaelMure** [comment]
You can change the default here: https://github.com/MichaelMure/WalletGenerator.net/blob/master/src/ninja.onload.js#L11

Build the project using grunt and you are good to go.
