### ISSUE TITLE
Add zcash support

### ISSUE THREAD

**Issue by amingilani** [walletgeneratornet/WalletGenerator.net#50]
Hello

Opening an issue because I don't have the time to do it myself, but someone might want to pick up the mantle. Zcash support is lacking.

**Comment by seanauriti** [comment]
Coin requests are now here: https://github.com/MichaelMure/WalletGenerator.net/wiki/Coin-Requests

P.S. I tried implementing ZCash and there was some issue.  Hopefully there is a workaround.

**Comment by MichaelMure** [comment]
Details on how to implement support for ZCash here: https://github.com/MichaelMure/WalletGenerator.net/issues/57#issuecomment-349482198

**Comment by MichaelMure** [comment]
Zcash is now supported.
