### ISSUE TITLE
Define WIF_Start and CWIF_Start

### ISSUE THREAD

**Issue by christiangrieger** [walletgeneratornet/WalletGenerator.net#7]
Hey there,

could you explain me or provide me with a javascript snippet that shows an example to define that both values?

I noticed that when i open a coin wallet and go to the debug console and type „dumpprivkey COINADDRESS“ i always get a private key in the compressed format. (CWIF_Start)
Here i can take the first letter that i need for the paper wallet compressed string (// 52 characters base58). Am i right? It will always be the compressed version on every wallet that is out or?

My problem is that i dont know how to get the uncompressed private key (WIF_Start) for a coin.

I hope you can help me.

Greetings,
Christian

**Comment by MichaelMure** [comment]
Hi,

Have a look here:
https://github.com/MichaelMure/WalletGenerator.net/wiki/How-to-add-a-new-currency

**Comment by christiangrieger** [comment]
Perfect :) thank you! I didnt know there is a Wiki.
