### ISSUE TITLE
BIP38 "The text you entered is not a valid Private Key"

### ISSUE THREAD

**Issue by mb-deihl** [walletgeneratornet/WalletGenerator.net#77]
Using Windows-10 and the Chrome browser, June 2017 I used walletgenerator.net to create a Bitcoin paper wallet.  3 months later upon trying to move the funds, I first verified the balance with Blockchain.info, still there, good.  Using walletgenerator.net: Wallet Detail; View Details, and entering the BIP38 encrypted Private Code that was generated and printed by this program, it begins with "6PfV" running 58 characters in length, I get the error message "The text  you entered is not a valid Private Key".  

Blockchain.info had no problem reading the key pair address printed by walletgenerator.net for that particular Private Key.

How can walletgenerator.net reject its own encryption result?  It doesn't even let me get to the point of verifying the BIP38 Passphrase.  I don't think BIP38 is the issue.

Another puzzling and interesting fact is that the printed wallet has the art format for a Bitcoin wallet and the title says "Bitcoin Paper Wallet Generator" but at the bottom left corner of the page, in small print is the stamp: "https://walletgenerator.net/?currency=Litecoin".  I had just created a Litecoin wallet prior to this Bitcoin wallet.  It was also BIP38 encoded, by the way and started with "6PfL".  That wallet decrypted properly and I swept those funds without issue.

Obviously when I changed the currency selection indicator from Litecoin to Bitcoin it caused the art to change over, but I wonder if there is crossed logic not completely switched from one coin to the other.

I have about $600 worth of BTC in the wallet, depending on the time of day.  I can't walk away from it, but it's not enough value for a recovery service to bother with.  Also what if this happens to others with much more at stake.  I don't think this is the same as some of the unresolved problems with BIP38 I see in other forums.

I sure would like to know why it happens and what a solution would be.  I have the physical evidence for anyone qualified to look at it.

**Comment by MichaelMure** [comment]
Hmmm,

First,  "https://walletgenerator.net/?currency=Litecoin" is the URL you used to go to the website. If you change the currency later, the URL is not updated, but that doesn't impact the behavior of the website.

How did you copy the encrypted private key from the paper wallet ? By hand ? Qr code ? Could it be that you made a mistake here ?

You can also try to decrypt your key using https://www.bitaddress.org. It should be exactly the same code without the (extremely small) changes to support other currencies.

Obviously, I wont ask you for the private key and the password to debug that ...

**Comment by mb-deihl** [comment]
Point 1) I’ll buy into that.

Question 1) I wrote the Private Key by keyboard into a spreadsheet for further handling.  I know that that is suspect, but the Private Key is printed on the wallet in 3 lines of 17 characters each line and the remaining 7 characters on line 4 making 58 total.  I have gone over these characters in small groups noting Caps and Lowers and Numbers so many times between the 14 point font spreadsheet copy and the paper version I’m close to memorizing it.  Because I have a copy I trust in the spreadsheet I use standard keystroke Cut and Paste to move it to the wallet generators offline.

Point 2)  I have used bitaddress.org and its clone bitcoinpaperwallet.com to try and decrypt the wallet more often than using walletgenerator.net. All have the same behavior: not valid Private Key.  I never get to the actual BIP38 verification.  The only difference in these versions is the look of the wallet. 

I will gladly send a copy of the printed wallet to you.  That way you will have everything you need.  The BIP38 Passphrase is handwritten on the wallet and the amount is still there I checked it a few hours ago 0.153737.  I trust you with it.  Hell I would love to give you a reward if you can crack it open.  The wallet recovery guy didn’t want to be bothered for its low balance ($600).  He must be getting rich.

If it was the passphrase not working, I was prepared to try about 20 variants of the one I wrote down.  But I don’t get that far.  It’s the encoded Private Key that is rejected.

Let me know how I can, reasonably safe, get you a copy of the printed wallet.

**Comment by MichaelMure** [comment]
Did you try scanning the qr code, just to be sure ? You can do it on the
wallet detail tab, there is a small icon.

Sending me the physical wallet will not be possible as I'm in a year long
travel around the world. If you feel confident, my email is on my github
profile: https://github.com/michaelmure

**Comment by mb-deihl** [comment]
Michael,
You were spot on.  I feel like an idiot not only for not questioning a I, L, or 1, turned out to be a 1 not I.  It took me longer to get QR working then it should have.  Anyway all's good; take the human out and it works almost always.  Enjoy the planet.  That sounds like a magnificent adventure.  You can close this issue; human error.  Thanks for your time.
Cheers!

**Comment by stevesbrain** [comment]
@mb-deihl So glad you were able to come to a happy resolution :D

**Comment by MichaelMure** [comment]
Yeah, happy ending !

Enjoy your money :-)
