### ISSUE TITLE
Change Darkcoin to DASH

### ISSUE THREAD

**Issue by mkinney** [walletgeneratornet/WalletGenerator.net#8]
Darkcoin was re-branded to DASH on March 25, 2015. Can you re-name the Darkcoin link to DASH?

Everything else is still the same regarding the DASH cryptocurrency. (BIP38 prefix is still a '6', leading character is an X, etc.)

See https://www.dashpay.io/news/darkcoin-is-now-dash/ for more info.

**Comment by MichaelMure** [comment]
Solved with #11
