### ISSUE TITLE
MUE wallet paper doesnt work

### ISSUE THREAD

**Issue by mirreoo** [walletgeneratornet/WalletGenerator.net#87]
Could you please fix the issue with MUE (MonetaryUnit) paper wallet? The address it generates is not recognized anywhere.
I've contacted exchanges and Monetary Unit about this, and they also do not recognize the public address that has been generated, I tried to generate 4 times.

**Comment by MichaelMure** [comment]
Hi,

Can you follow this https://github.com/MichaelMure/WalletGenerator.net/wiki/How-to-add-a-new-currency and report with the values you find ?

For reference, the current values are "MonetaryUnit", 0x0f, 0x8f, "5", "N".

**Comment by MichaelMure** [comment]
Hopefully fixed with #82. Not released yet.

**Comment by mirreoo** [comment]
the ones i generated before were 7L, 0x73 and 79r
