### ISSUE TITLE
please add: Stratis

### ISSUE THREAD

**Issue by fredfalcon** [walletgeneratornet/WalletGenerator.net#91]

**Comment by MichaelMure** [comment]
Hello,

Please consider contributing it yourself: https://github.com/MichaelMure/WalletGenerator.net/wiki/How-to-add-a-new-currency

**Comment by seanauriti** [comment]
I gave it a shot, here is what I came up with - when I went to sweep the wallet it did not recognize the private key format - 

janin.currency.createCurrency ("Stratis",             0x3f, 0x4, "[89A]", "[abcdefghi]", "ScMNGH91SpNwbRDeK8vYXXJ3aYpwBr9Pen"),
