### ISSUE TITLE
TrezarCoin line of code/logo/template

### ISSUE THREAD

**Issue by cellendhyl25** [walletgeneratornet/WalletGenerator.net#99]
janin.currency.createCurrency ("TrezarCoin",          0x42, 0xC2, "9",    "V"    , "Tw1jsLJKfmcosUCkJuMevdLLJob9wD7PSE"),

Template

![trezarcoin](https://user-images.githubusercontent.com/26672494/32626488-c642f14e-c58f-11e7-94a6-8d0e960a8fa5.png)

Logo
![trezarcoin](https://user-images.githubusercontent.com/26672494/32626510-d4315aac-c58f-11e7-8b1b-4751c49e88ae.png)

**Comment by MichaelMure** [comment]
Merged manually: https://github.com/MichaelMure/WalletGenerator.net/commit/da4e60c981ac4e413c1909c4822ddc6e71b06a8e
